### ISSUE TITLE
Prepare Analytical Dataset Assignment

### ISSUE THREAD

**Issue by huq23** [huq23/SOC513_Project#3]
@AaronGullickson Professor, 
I pushed my organize_data script in the git. I can see my three new constructed datasets in the folder on my desktop, but they are not appearing when I want to push them on git. Could you please help? I am attaching the screenshot.

![Screenshot 2024-05-21 123347](https://github.com/huq23/SOC513_Project/assets/146165957/15beb0af-b612-428e-b681-5a14cb0c0dbc)

**Comment by AaronGullickson** [comment]
Files in the `data_constructed` directory are ignored by design. These files are artifacts that may change over time so we don't want to commit them. Re-running the organize data script is sufficient to get them locally. So, all I need is the script and the raw data to get them.

**Comment by huq23** [comment]
Completed Analytical Dataset Assignment @AaronGullickson. Thank you, Professor, for your answer!

**Comment by AaronGullickson** [comment]
@huq23 See my comments on issue #2
