### ISSUE TITLE
Lab Notebook Assignment

### ISSUE THREAD

**Issue by huq23** [huq23/SOC513_Project#4]
@AaronGullickson Dear Professor, I am uploading the analysis.qmd file. could you please check and is that what you are asking for lab notebook assignment? Additionally, I am facing some problem and need your help.
1. when I am trying to render the qmd file it was unable to generate the table and give me an error message. ( I am attaching the screenshot here). 
2. How could I modify the coefficient names? Should I use modelsummary to write the variable names in the regression table?
3.  I found that when I am using log (the elasticity model), the regression result is easier to describe. Should I use that model also? Do you think is it a good approach?
4. Finally, I am not sure but want your suggestion on the final merge data, since I am considering three years data sets, should I take the average values of all variables for analysis? 
![Screenshot 2024-06-04 122811] (https://github.com/huq23/SOC513_Project/assets/146165957/04fea72a-5d06-4bd6-bb53-5ee1834fe8b2)

**Comment by AaronGullickson** [comment]
1. The `knitreg` function doesn't work with quarto unfortunately. When you want to render the document you will need to change those calls to `htmlreg` for the analysis (which is HTML output) and `texreg` for the paper (which is PDF). The other option would be to use modelsummary which will work fine across any rendering format. Its the same format: `modelsummary(list(model1, model2, model3))`. The [website](https://modelsummary.com/articles/modelsummary.html) includes all kinds of information about how to customize the output.
2. If you use texreg, you can use the custom.coef.names argument. For `modelsummary` follow [these instructions](https://modelsummary.com/articles/modelsummary.html#coef_rename). 
3. Its a little unusual to log a percent, but there is nothing inherently wrong with that approach. Logging the crime rate probably makes more sense. 
4. You have repeat observations on the same units, so you are technically violating the IID assumption. A simple fix would be to use cluster robust standard errors. You can find some example code [here](https://lost-stats.github.io/Model_Estimation/Statistical_Inference/Nonstandard_Errors/clustered_se.html#:~:text=Cluster%2Drobust%20standard%20errors%20for,function%20from%20the%20lmtest%20package.)

**Comment by huq23** [comment]
Complete Lab Notebook. @AaronGullickson Professor, thank you for your guidance!
