### ISSUE TITLE
Error in Full Paper 

### ISSUE THREAD

**Issue by huq23** [huq23/SOC513_Project#5]
@AaronGullickson Professor, 
I am facing problem while rendering the full paper particularly while I am adding the second table it is unable to render. I have pushed it in the git. Could you please check and help me?

**Comment by AaronGullickson** [comment]
It works fine for me, although there is an empty line between the code chunk and the start of your code chunk parameters on line 145. Remove that empty line and the cross-ref and caption works properly.

**Comment by huq23** [comment]
@AaronGullickson Thank you for your response. It is not rendering from my end. I have removed the line gap. Should I need to do anything in addition?

**Comment by AaronGullickson** [comment]
What kind of error do you get?

**Comment by huq23** [comment]
Complete. 
@AaronGullickson Professor, I have fixed it and submitted. Thank you for your help!
